In [1]:
import pandas as pd
import numpy as np

**1. Cargad el csv que guardasteis ayer.**

>Antes de seguir con las preguntas, este DataFrame está terriblemente sucio. En las próximas sesiones lo iremos limpiando. Para evitar posibles errores con los nulos vamos a eliminar todos los nulos del DataFrame.

>Para ello vamos a utilizar el método .dropna() de pandas. Tendréis que ejecutar la siguiente línea de código para eliminar los nulos del DataFrame y poder seguir haciendo el resto de los ejercicios.

In [2]:
df_attack2 = pd.read_csv('./attack2.csv',index_col=0)

pd.options.display.max_columns = None #para ver todas las columnas

df_null= df_attack2.dropna(inplace = True) #Hemos eliminado nulls(nan)

df_attack2.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...

**2. ¿Cuál es el número de ataques que se han producido en Estados Unidos?**

In [3]:
attackusa = df_attack2[df_attack2['country'] == 'USA']
attackusa.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.31,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
2017.12.31,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2017.11.24,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...

**3. ¿Y en España?**

In [4]:
attackspain = df_attack2[df_attack2['country'] == 'SPAIN']
attackspain.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2017.08.26.b,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...
2016.07.29,2016.0,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,11h30,Blue shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2015.08.18.a,2015.0,Invalid,SPAIN,Alicante,"Poniente Beach, Benidorm",Swimming,male,M,10,11h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
2010.07.16.b,2010.0,Provoked,SPAIN,Grand Canary Island,"Sardina del Norte, Gáldar",Swimming,male,M,9,19h15,Angel shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1993.09.03,1993.0,Unprovoked,SPAIN,Costa Blanca,"Playa de las Arenas, Valencia",Swimming,Jorge Durich Heredia (or Hernandez),M,69,08h00,1.2 m [4'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...

**- 3.1 ¿En qué regiones se han producido los ataques?**

In [5]:
attackspain["area"].unique()

array(['Castellón', 'Alicante Province', 'Alicante',
       'Grand Canary Island', 'Costa Blanca'], dtype=object)

**- 3.2 ¿Cuántos ataques se han producido en cada área?**

In [6]:
attackspain["area"].value_counts()

Castellón              1
Alicante Province      1
Alicante               1
Grand Canary Island    1
Costa Blanca           1
Name: area, dtype: int64

**4.  Extraed un DataFrame nuevo con los ataques que se han producido en Australia y Estados Unidos.** 

📌 Nota Este ejercicio se puede resolver usando dos condiciones de filtrado o usando el método isin().
Hacedlo con ambas herramientas.

In [7]:
attack34 = df_attack2[((df_attack2['country'] == 'USA')) | ((df_attack2['country'] == 'AUSTRALIA'))]
attack34.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.25.a,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.31,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...

- **4.1 ¿Cuántos ataques se han producido en cada pais?**

In [8]:
attack3 = df_attack2[df_attack2["country"].isin(["USA" , "AUSTRALIA"])]
attack3.head()
attack3["country"].value_counts()

USA          719
AUSTRALIA    324
Name: country, dtype: int64

- **4.2 ¿Ha habido ataques en Australia a gente que estuviera remando (lo encontrareis como Paddling en el DataFrame en la columna activity)?**

In [9]:
attack4 = df_attack2[((df_attack2['country'] == 'AUSTRALIA')) & ((df_attack2['activity'] == 'Paddling'))]
attack4.head()
# En Australia no se practica Paddling, por lo que vemos, en USA es más popular.

Empty DataFrame
Columns: [year, type, country, area, location, activity, name, sex , age, time, species , href]
Index: []

- **4.3 ¿Cuántos ataques se han producido en Australia antes del 2000?**

In [10]:
attack5 = df_attack2[((df_attack2['country'] == 'AUSTRALIA')) & ((df_attack2['year'] < 2000))]
attack5.head()
attack5["year"].value_counts()

1961.0    9
1959.0    6
1960.0    5
1989.0    5
1963.0    5
         ..
1947.0    1
1965.0    1
1952.0    1
1953.0    1
1880.0    1
Name: year, Length: 66, dtype: int64

- **4.4 ¿Y después del 2000?**

In [11]:
attack6 = df_attack2[((df_attack2['country'] == 'AUSTRALIA')) & ((df_attack2['year'] > 2000))]  #¿Que pasa con el 2000? ¿Por que nadie le quiere? T_T
attack6.head()
attack6["year"].value_counts()

2012.0    17
2015.0    14
2009.0    13
2011.0    12
2007.0    12
2016.0    11
2014.0    10
2008.0    10
2005.0     9
2017.0     9
2006.0     9
2013.0     8
2004.0     7
2018.0     7
2010.0     7
2002.0     5
2003.0     4
2001.0     3
Name: year, dtype: int64

**5. Extraed unicamente los ataques a mujeres.**

In [12]:
attackgirls= df_attack2[df_attack2['sex '] == 'F']
attackgirls.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.02.23,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2017.12.31,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2017.10.22,2017.0,Unprovoked,AUSTRALIA,South Australia,Normanville,Kayaking / Fishing,Sarah Williams,F,15,Afternoon,"White shark, 4.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2017.10.05,2017.0,Unprovoked,USA,Hawaii,"Kamaole Beach Park, Maui",Snorkeling,female,F,40,12h30,8' shark,http://sharkattackfile.net/spreadsheets/pdf_di...

**6. ¿Cuántas mujeres fueron atacadas en España?**

In [13]:
attackgirlsspain = df_attack2[((df_attack2['country'] == 'SPAIN')) & ((df_attack2['sex '] == 'F'))]
attackgirlsspain.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2017.08.26.b,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...

**7. Extraed los ataques que se hayan producido en el año 2000, 1997 y 2006. Utilizad el método isin() para resolver este ejercicio.**

In [14]:
attack7 = df_attack2[df_attack2["year"].isin([2000, 1997, 2006] )]
attack7.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2006.12.18,2006.0,Unprovoked,AUSTRALIA,Victoria,"Winki Pop, Bells Beach",Surfing,Peter Galvin,M,25,20h00,2.5 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2006.12.11,2006.0,Unprovoked,NEW ZEALAND,North Island,"Raglan, Manu Bay",Surfing,Elliot Paerata-Reid,M,10,11h00,2 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2006.12.10,2006.0,Unprovoked,USA,California,"Dillon Beach, Marin County",Surfing,Royce Fraley,M,43,11h50,"White shark, 12' to 15'",http://sharkattackfile.net/spreadsheets/pdf_di...
2006.12.06,2006.0,Provoked,SOUTH AFRICA,KwaZulu-Natal,Cape Vidal,Fishing,Peter Willoughby,M,25,"""Evening""","Raggedtooth shark, 150-kg",http://sharkattackfile.net/spreadsheets/pdf_di...
2006.12.02,2006.0,Unprovoked,AUSTRALIA,Western Australia,Wharton Beach,Body boarding,Zac Golebiowski,M,15,07h30,"White shark, 5m",http://sharkattackfile.net/spreadsheets/pdf_di...

**8.Si extraemos los valores únicos de la columna species nos podemos dar cuenta que está un poco sucia y extraer informacion útil de la misma. En este ejercicio tendréis que extraer los ataques que han ocurrido por tiburón blanco (lo encontraremos en la columna species como algo que contenga white o White)**. 

👍🏻 *Usad el método str.contains() para resolver este ejercicio.*

In [15]:
attacktiburon = df_attack2[df_attack2['species '] == 'white']
attacktiburon['species '].unique()

array([], dtype=object)

In [16]:
patron2 = 'White' #Probar a usar regex

attacktiburon = df_attack2[df_attack2["species "].str.contains(patron2, regex=True)]
attacktiburon. head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.22,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,33,09h40,"White shark, 2.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.03,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,Ross Spowart,M,19,15h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2017.11.24,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2017.10.22,2017.0,Unprovoked,AUSTRALIA,South Australia,Normanville,Kayaking / Fishing,Sarah Williams,F,15,Afternoon,"White shark, 4.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...

**9. Extraed ahora los ataques por tiburón blanco o tigre. Utilizad el método str.contains() para resolver este ejercicio.**

In [17]:
df_attack2['species '].values[0:] #Queriamos ver todos los valores de "Species"

array(['White shark', 'Tiger shark', "Bull shark, 6'", ..., "12' shark",
       'Bull shark', 'Identified as C. gangeticus by Dr. J. Fayrer'],
      dtype=object)

In [18]:
blanco = 'White'
tigre = 'Tiger'

attacktiburon = df_attack2[(df_attack2["species "].str.contains(tigre,regex=True))|(df_attack2["species "].str.contains(blanco,regex=True))]
attacktiburon.head()

,year,type,country,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.28.b,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,male,M,30,10h40,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.23,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,Ahmed Rasheed,M,32,21h50,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.22,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,33,09h40,"White shark, 2.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...

**10. Utilizando la columna de 'year' cread una nueva columna llamada siglo que tiene siglo-XX o siglo-XXI. Donde el año sea menor que 2000 pondremos siglo-XX y el resto de los años siglo-XXI.**

In [19]:
condiciones = [
            (df_attack2['year'] < 2000), 
            (df_attack2['year'] >= 2000)
]
opciones = ['Siglo-XX', 'Siglo-XXI'] 
df_attack2['siglo'] = np.select(condiciones, opciones)
df_attack2.head()

#Hemos conocido 3 formas diferentes de añadir columnas con condiciones, con  SELECT, WHERE y esta última.O una condición IF.

,year,type,country,area,location,activity,name,sex,age,time,species,href,siglo
case number,,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,Siglo-XXI
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,Siglo-XXI
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,Siglo-XXI
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,Siglo-XXI
2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,Siglo-XXI

In [20]:
#Hemos decidido cambiar su posició,(con .pop)para que sea más proxima 
#a la columna sobre la que se han tomado los datos de referencia para las condiciones.
nueva_posicion = df_attack2.pop('siglo') 

df_attack2.insert(3, 'siglo', nueva_posicion)
df_attack2.head()

,year,type,country,siglo,area,location,activity,name,sex,age,time,species,href
case number,,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,Siglo-XXI,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Siglo-XXI,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Siglo-XXI,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Siglo-XXI,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.13.a,2018.0,Invalid,ENGLAND,Siglo-XXI,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...